name: Test and Static Analysis (Other Branches)

on:
  push:
    branches-ignore:
      - develop
      - master

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4']

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: PHP Version Check
        run: php -v

      - name: Validate Composer Test JSON
        run: COMPOSER=composer-test.json composer validate --no-check-lock --strict

      - name: Install Dependencies
        run: COMPOSER=composer-test.json composer install --no-interaction --prefer-dist

      - name: PHP Lint
        run: ./vendor/bin/parallel-lint src tests

      - name: Unit tests
        run: |
          mkdir -p build/logs
          ./vendor/bin/phpunit --version
          ./vendor/bin/phpunit --configuration tests/phpunit.xml

  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer:v2

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: PHP Version Check
        run: php -v

      - name: Validate Composer JSON
        run: composer validate

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: PHP Lint
        run: ./vendor/bin/parallel-lint src tests

      - name: PHP Code Sniffer
        run: |
          ./vendor/bin/phpcs --version
          ./vendor/bin/phpcs --ignore=vendor --standard=tools/coding_standard.xml -s .

      - name: PHP Stan
        run: |
          ./vendor/bin/phpstan --version
          ./vendor/bin/phpstan analyze -c tools/phpstan.neon

      - name: Psalm
        run: |
          ./vendor/bin/psalm --version
          ./vendor/bin/psalm -c tools/psalm.xml

      - name: Composer Unused Dependencies
        run: ./vendor/bin/composer-unused

      - name: Composer Require Checker
        run: ./vendor/bin/composer-require-checker check composer.json

      - name: Composer Audit
        run: composer audit --no-interaction
